org: diegosantosouza
app: authorization-serverless-http-api
service: authorization-serverless-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
